website/auth.py
from asyncio.windows_events import NULL
from flask import flash
from flask_sqlalchemy import SQLAlchemy
from flask import Blueprint,render_template,request,redirect,url_for
import datetime
from website.models import Blood
from website import db
from flask_login import login_user , login_required , logout_user ,current_user


auth = Blueprint('auth',__name__)

@auth.route('/login',methods=['GET','POST'])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')

       
        user = Blood.query.filter_by(email=email).first()
        if user:
            if(user.password == password):
                
                login_user(user, remember=True)
                if(user.email == 'admin@123' or user.userrole == 1):
                    return redirect ('admindashboard')
                else:
                    return redirect('userdashboard')
            else:
                flash('incorrect password',category='error')
        else:
            flash('email does not exist',category='error')            
    return render_template("login.html")



@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

website/views.py
from flask import Blueprint,render_template,request,redirect,url_for
from asyncio.windows_events import NULL
from flask import flash
from flask_sqlalchemy import SQLAlchemy 
from sqlalchemy import update
import datetime
from website.models import Blood 
from website import db
from flask_login import  login_required , current_user

views = Blueprint('views',__name__)


@views.route('/')
def home():
    return render_template("home.html")

@views.route('/search_blood',methods=['GET','POST'])
def search_blood():
    if request.method == 'POST':
        searchbyblood = request.form.get("searchbyblood")
        searchbylocation = request.form.get("city")
        if(searchbyblood != NULL and searchbylocation != NULL ):
            donors = (Blood.query.filter_by(bloodgroup=searchbyblood).all() and Blood.query.filter_by(city=searchbylocation).all())
            return render_template('search_blood.html', donors = donors)
        if(searchbyblood != NULL and searchbylocation == NULL):
            donors = Blood.query.filter_by(bloodgroup=searchbyblood).all()
            return render_template('search_blood.html', donors = donors)
    return render_template("search_blood.html")

@views.route('/editdashboard',methods=['GET','POST'])
@login_required
def editdashboard():
    if request.method == 'POST':
        uname = request.form.get("uname")
        sex =request.form.get("sex")
        bloodgroup = request.form.get("bloodgroup")
        address = request.form.get("address")
        city = request.form.get("city")
        email = request.form.get("email")
        contact = request.form.get("contact")

        blood = Blood.query.filter_by(email=email).first()
        blood.uname=uname
        blood.sex=sex
        blood.bloodgroup=bloodgroup
        blood.address=address
        blood.city=city
        blood.email=email
        blood.contact=contact

        db.session.commit() 

    return render_template('editdashboard.html',user=current_user)

@views.route('/userdashboard')
@login_required
def userdashboard():
    return render_template('userdashboard.html',user=current_user)

@views.route('/admindashboard')
@login_required
def admindashboard():
    return render_template('admindashboard.html',user=current_user)

@views.route('/changeadminpassword',methods = ['GET','POST'])
@login_required
def changeadminpassword():
    if request.method == 'POST':
        password = request.form.get("password")
        password1 = request.form.get("password1")
        if(password == password1):
            email = request.form.get("email")
            blood = Blood.query.filter_by(email=email).first()
            blood.password=password
            db.session.commit()
            flash('password updated successfully', category='sucess')
        else:
            flash('passwords don\'t match', category='error')

    return render_template('changeadminpassword.html',user=current_user)

@views.route('/addadmin', methods=['GET','POST'])
@login_required
def addadmin():
    if request.method == 'POST':
        uname = request.form.get("uname")
        password = request.form.get("password")
        password1 = request.form.get("password1")
        dob1 = request.form.get("dob")
        dob2 = datetime.datetime.strptime(dob1, "%Y-%m-%d")
        sex = request.form.get("sex")
        bloodgroup = request.form.get("bloodgroup")
        address = request.form.get("address")
        city = request.form.get("city")
        email = request.form.get("email")
        contact = request.form.get("contact")

        if len(uname) < 2:
            flash('Name  must be greater than 1 characters', category='error')
        elif len(password1) < 7:
            flash('passwords must be atleast 7 characters', category='error')    
        elif password != password1:
            flash('passwords don\'t match', category='error')
        elif (dob1 == NULL ): 
            flash('dob must be filled', category='error')    
        elif (sex == "Select"): 
            flash('sex must be filled', category='error')
        elif (bloodgroup == "Select"): 
            flash('bloodgroup must be filled' , category ='error') 
        elif (address == NULL): 
            flash('address must be filled' , category='error')  
        elif (city == NULL): 
            flash('city must be filled' ,category='error') 
        elif len(email) < 2:
            flash('email must be greater than 5 characters',category='error')                        
        elif len(contact) != 10:
            flash('contact must conatain 10 characters',category='error')
        else:
            flash('Account created', category='sucess')
            blood = Blood(uname=uname,password=password,dob=dob2,sex=sex,bloodgroup=bloodgroup,address=address,city=city,email=email,contact=contact,userrole=1)
            db.session.add(blood)
            db.session.commit()
    return render_template('addadmin.html',user=current_user)

@views.route('/<int:id>/edituser',methods=['GET','POST'])
@login_required
def edituser(id):
    donors = Blood.query.filter_by(id=id).first() 
    if request.method == 'POST':
        uname = request.form.get("uname")
        sex =request.form.get("sex")
        bloodgroup = request.form.get("bloodgroup")
        address = request.form.get("address")
        city = request.form.get("city")
        email = request.form.get("email")
        contact = request.form.get("contact")
        donors.uname=uname
        donors.sex=sex
        donors.bloodgroup=bloodgroup
        donors.address=address
        donors.city=city
        donors.email=email
        donors.contact=contact

        db.session.commit() 

    return render_template('edituser.html',donors=donors,user=current_user)

@views.route('/<int:id>/deleteuser',methods=['GET','POST'])
@login_required
def deleteuser(id):
    donors = Blood.query.filter_by(id=id).first()
    if request.method == 'POST':
        if donors:
            db.session.delete(donors)
            db.session.commit()
            return redirect(url_for('views.admineditdashboard'))
        
    return render_template('deleteuser.html',donors=donors ,user=current_user)

@views.route('/admineditdashboard')
@login_required
def admineditdashboard():
    donors = Blood.query.all()
    donors.pop(1)
    return render_template('admineditdashboard.html',donors=donors,user=current_user)


@views.route('/changepassword',methods=['GET','POST'])
@login_required
def changepassword():
    if request.method == 'POST':
        password = request.form.get("password")
        password1 = request.form.get("password1")
        if(password == password1):
            email = request.form.get("email")
            blood = Blood.query.filter_by(email=email).first()
            blood.password=password
            db.session.commit()
            flash('password updated successfully', category='sucess')
        else:
            flash('passwords don\'t match', category='error')

    return render_template('changepassword.html',user=current_user)

@views.route('/<int:id>/lastdonationdate',methods=['GET','POST'])
@login_required
def lastdonationdate(id):
    if request.method == 'POST':
        lastdonationdate = request.form.get("lastdonationdate")
        date = datetime.datetime.strptime(lastdonationdate, "%Y-%m-%d")
        blood = Blood.query.filter_by(id=id).first()
       
        blood.Lastdonationdate=date
        db.session.commit()
        flash('Last donation date updated sucessfully',category='sucess') 
        
    return render_template('lastdonationdate.html',user=current_user)

@views.route('/uploadhealthcertificate')
@login_required
def uploadhealthcertificate():
    return render_template('uploadhealthcertificate.html',user=current_user)


@views.route('/register',methods=['GET','POST'])
def register():
    if request.method == 'POST':
        uname = request.form.get("uname")
        password = request.form.get("password")
        password1 = request.form.get("password1")
        dob1 = request.form.get("dob")
        dob2 = datetime.datetime.strptime(dob1, "%Y-%m-%d")
        sex = request.form.get("sex")
        bloodgroup = request.form.get("bloodgroup")
        address = request.form.get("address")
        city = request.form.get("city")
        email = request.form.get("email")
        contact = request.form.get("contact")
        
        if len(uname) < 2:
            flash('Name  must be greater than 1 characters', category='error')
        elif len(password1) < 7:
            flash('passwords must be atleast 7 characters', category='error')    
        elif password != password1:
            flash('passwords don\'t match', category='error')
        elif (dob1 == NULL ): 
            flash('dob must be filled', category='error')    
        elif (sex == "Select"): 
            flash('sex must be filled', category='error')
        elif (bloodgroup == "Select"): 
            flash('bloodgroup must be filled' , category ='error') 
        elif (address == NULL): 
            flash('address must be filled' , category='error')  
        elif (city == NULL): 
            flash('city must be filled' ,category='error') 
        elif len(email) < 2:
            flash('email must be greater than 5 characters',category='error')                        
        elif len(contact) != 10:
            flash('contact must conatain 10 characters',category='error')
        else:
            flash('Account created', category='sucess')
            blood = Blood(uname=uname,password=password,dob=dob2,sex=sex,bloodgroup=bloodgroup,address=address,city=city,email=email,contact=contact)
            db.session.add(blood)
            db.session.commit()
            
        return render_template('register.html') 
    return render_template("register.html")      

website/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
    rel="stylesheet"
    href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
    crossorigin="anonymous"
    />
    <title>{% block title %}home{% endblock %}</title>
    </head>
    <body>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbar"
      >
      <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar">
        <div class="navbar-nav">
          <a class="nav-item nav-link" id="home" href="/">Home</a>
          <a class="nav-item nav-link" id="login" href="/login">Login</a>
          <a class="nav-item nav-link" id="register" href="/register">Register</a>
          <a class="nav-item nav-link" id="search_blood" href="/search_blood">Search blood</a>
      </div>
      </div>
        </nav>
        {% with messages = get_flashed_messages(with_categories=true) %} {% if
          messages %} {% for category, message in messages %} {% if category ==
          'error' %}
          <div class="alert alert-danger alter-dismissable fade show" role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          {% else %}
          <div class="alert alert-success alter-dismissable fade show" role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          {% endif %} {% endfor %} {% endif %} {% endwith %}

        <div class="container">
          {% block content %}
          {% endblock %}
          </div>
      <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
    src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"
  ></script>
  <script
     type="text/javascript"
     src="{{ url_for('static',filename='index.js')}}"
     ></script>
     <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
     <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
    </body>    
</html>    

website/templates/changepassword.html
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
  rel="stylesheet"
  href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
  integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
  crossorigin="anonymous"
/>
<link
rel="stylesheet"
href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
crossorigin="anonymous"
/>
<link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">
    <title>Dashboard</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename = 'style.css') }}">
 
  </head>
  <body>
    
    <div class="area">
        <center>
        {% with messages = get_flashed_messages(with_categories=true) %} {% if
            messages %} {% for category, message in messages %} {% if category ==
            'error' %}
            <div class="alert alert-danger alter-dismissable fade show" role="alert">
              {{ message }}
              <button type="button" class="close" data-dismiss="alert">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            {% else %}
            <div class="alert alert-success alter-dismissable fade show" role="alert">
              {{ message }}
              <button type="button" class="close" data-dismiss="alert">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            {% endif %} {% endfor %} {% endif %} {% endwith %}
            </center>
        <div class="container">
            <div class="container">
                <div class="container">

                    <form action = '/changepassword' method= 'POST'> 
                        <div class="form-group">
                            <!--label for="email">Email</label-->
                            <input type="email" class="form-control" id="email"
                                placeholder="Enter Email" name="email" value="{{current_user.email}}" hidden>
                        </div>  
                        <div class="form-group"> 
                            <label for="password">Password</label> 
                            <input type="password" class="form-control" id="password" placeholder="Enter the new password" name="password"> 
                        </div> 
                        <div class="form-group"> 
                            <label for="password">Confirm Password</label> 
                            <input type="password" class="form-control" id="password1" placeholder="Confirm new Password" name="password1"> 
                        </div>

                        <button type="submit" class="btn bg-success"> Update </button>
                     </form>     
       
    </div><nav class="main-menu">
        
            <ul>
                <li>
                    <a href="{{url_for('views.userdashboard')}}">
                        <i class="fa fa-home fa-2x"></i>
                        <span class="nav-text">
                           Detail
                        </span>
                    </a>
                  
                </li>
                
               <li class="has-subnav">
                    <a href="{{url_for('views.editdashboard')}}">
                        <i class="fa fa-edit fa-2x"></i>
                        <span class="nav-text">
                            Edit details
                        </span>
                    </a>
                    
                </li>
                <li class="has-subnav">
                    <a href="#">
                       <i class="fa fa-lock fa-2x"></i>
                        <span class="nav-text">
                            Change password
                        </span>
                    </a>
                    
                </li>
                <li class="has-subnav">
                    <a href="{{url_for('views.uploadhealthcertificate')}}">
                       <i class="fa fa-upload fa-2x"></i>
                        <span class="nav-text">
                            Upload health certificate
                        </span>
                    </a>
                    
                </li>
                <li class="has-subnav">
                    <a href="/{{current_user.id}}/lastdonationdate">
                       <i class="fa fa-tint fa-2x"></i>
                        <span class="nav-text">
                            Last donation date
                        </span>
                    </a>
                   
                </li>
                <!--li>
                    <a href="#">
                        <i class="fa fa-film fa-2x"></i>
                        <span class="nav-text">
                            Surveying Tutorials
                        </span>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <i class="fa fa-book fa-2x"></i>
                        <span class="nav-text">
                           Surveying Jobs
                        </span>
                    </a>
                </li>
                <li>
                   <a href="#">
                       <i class="fa fa-cogs fa-2x"></i>
                        <span class="nav-text">
                            Tools & Resources
                        </span>
                    </a>
                </li>
                <li>
                   <a href="#">
                        <i class="fa fa-map-marker fa-2x"></i>
                        <span class="nav-text">
                            Member Map
                        </span>
                    </a>
                </li>
                <li>
                    <a href="#">
                       <i class="fa fa-info fa-2x"></i>
                        <span class="nav-text">
                            Documentation
                        </span>
                    </a>
                </li-->
            </ul>
            
            <ul class="logout">
                <li>
                   <a href="{{url_for('auth.logout')}}">
                         <i class="fa fa-power-off fa-2x"></i>
                        <span class="nav-text">
                            Logout
                        </span>
                    </a>
                </li>  
            </ul>
            
        </nav>
        
        <script
        src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"
      ></script>
      <script
        src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"
      ></script>
      <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
   
         
</body>
    </html>

website/templates/home.html
{% extends "base.html" %}{% block title %}Home{% endblock %}
{% block content %}
<br>
<center><h1>WELCOME TO BLOOD DONATION SYSTEM</h1></center><br><br>

<img src="../static/blood.gif" height="500" width="500">




{% endblock %}

website/templates/lastdonationdate.html
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
  rel="stylesheet"
  href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
  integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
  crossorigin="anonymous"
/>
<link
rel="stylesheet"
href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
crossorigin="anonymous"
/>
<link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">
    <title>Dashboard</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename = 'style.css') }}">
    <style>
        *{
            font-family: sans-serif;
        }
        .content-table {
            border-collapse: collapse;
            margin: 28px 0;
            font-size: 1.8em;
            min-width: 500px;
            border-radius: 5px 5px 0 0;
            overflow: hidden;
            box-shadow: 0 0 20px rgba(0, 0, 0, 0.15);
        }
        .content-table tr th {
            background-color: #009879;
            color: #ffffff;
            text-align: left;
            font-weight: bold;
        }
        .content-table th,
.content-table td {
    padding: 12px 15px;
}
.content-table tbody tr {
    border-bottom: 1px solid #dddddd;
} 
.content-table tbody tr:nth-of-type(even) {
    background-color: #f3f3f3;
} 
.content-table tbody tr.active-row {
    font-weight: bold;
    color: #009879;
}
     
    </style>   
  </head>
  <body>
    
    <div class="area">
        <div class="container">
            <div class="container">
                <div class="container">
                   
                    <form action = "/{{current_user.id}}/lastdonationdate" method= 'POST'>  
                        <div class="form-group">
                            <!--label for="email">Email</label-->
                            <input type="email" class="form-control" id="email"
                                placeholder="Enter Email" name="email" value="{{current_user.email}}" hidden>
                        </div>    
                        <div class="form-group">
                            <center>
                                {% with messages = get_flashed_messages(with_categories=true) %} {% if
                                    messages %} {% for category, message in messages %} {% if category ==
                                    'error' %}
                                    <div class="alert alert-danger alter-dismissable fade show" role="alert">
                                      {{ message }}
                                      <button type="button" class="close" data-dismiss="alert">
                                        <span aria-hidden="true">&times;</span>
                                      </button>
                                    </div>
                                    {% else %}
                                    <div class="alert alert-success alter-dismissable fade show" role="alert">
                                      {{ message }}
                                      <button type="button" class="close" data-dismiss="alert">
                                        <span aria-hidden="true">&times;</span>
                                      </button>
                                    </div>
                                    {% endif %} {% endfor %} {% endif %} {% endwith %}
                                    </center>
                            <center>
                            <label for="lastdonationdate">Enter the last donation date </label>
                            <input type="date" class="form-control" id="lastdonationdate"
                                placeholder = "Enter the last donation date" name="lastdonationdate">
                            </center> <br>
                            <button type="submit" class="btn bg-success"> Update </button> 
                        </div>    
                    </form>
                    
                    <table class="content-table">
                        <tr>
                            <th>Last donation date</th>
                            <td>{{current_user.Lastdonationdate}}</td>
                        </tr>
                    </table>
                    
    </div><nav class="main-menu">
        
            <ul>
                <li>
                    <a href="{{url_for('views.userdashboard')}}">
                        <i class="fa fa-home fa-2x"></i>
                        <span class="nav-text">
                           Detail
                        </span>
                    </a>
                  
                </li>
                
               <li class="has-subnav">
                    <a href="{{url_for('views.editdashboard')}}">
                        <i class="fa fa-edit fa-2x"></i>
                        <span class="nav-text">
                            Edit details
                        </span>
                    </a>
                    
                </li>
                <li class="has-subnav">
                    <a href="{{url_for('views.changepassword')}}">
                       <i class="fa fa-lock fa-2x"></i>
                        <span class="nav-text">
                            Change password
                        </span>
                    </a>
                    
                </li>
                <li class="has-subnav">
                    <a href="{{url_for('views.uploadhealthcertificate')}}">
                       <i class="fa fa-upload fa-2x"></i>
                        <span class="nav-text">
                            Upload health certificate
                        </span>
                    </a>
                    
                </li>
                <li class="has-subnav">
                    <a href="#">
                       <i class="fa fa-tint fa-2x"></i>
                        <span class="nav-text">
                            Last donation date
                        </span>
                    </a>
                   
                </li>
                <!--li>
                    <a href="#">
                        <i class="fa fa-film fa-2x"></i>
                        <span class="nav-text">
                            Surveying Tutorials
                        </span>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <i class="fa fa-book fa-2x"></i>
                        <span class="nav-text">
                           Surveying Jobs
                        </span>
                    </a>
                </li>
                <li>
                   <a href="#">
                       <i class="fa fa-cogs fa-2x"></i>
                        <span class="nav-text">
                            Tools & Resources
                        </span>
                    </a>
                </li>
                <li>
                   <a href="#">
                        <i class="fa fa-map-marker fa-2x"></i>
                        <span class="nav-text">
                            Member Map
                        </span>
                    </a>
                </li>
                <li>
                    <a href="#">
                       <i class="fa fa-info fa-2x"></i>
                        <span class="nav-text">
                            Documentation
                        </span>
                    </a>
                </li-->
            </ul>
            
            <ul class="logout">
                <li>
                   <a href="{{url_for('auth.logout')}}">
                         <i class="fa fa-power-off fa-2x"></i>
                        <span class="nav-text">
                            Logout
                        </span>
                    </a>
                </li>  
            </ul>
            
        </nav>
        
        <script
        src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"
      ></script>
      <script
        src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"
      ></script>
      <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
   
         
</body>
    </html>